### ISSUE TITLE
pls update charge-lnd

### ISSUE THREAD

**Issue by thool2b3** [accumulator/charge-lnd#109]
thank you for providing lightning shell as a collection of useful tools. 
Now I would kindly ask you to consider updating lightning shell with the most recent version of charge-lnd v0.2.13.
I got the following error when I used strategy ignore-fees: 
_Unknown strategy 'ignore_fees' in policy 'Opener-HTLC-Slow'
Error executing strategy 'ignore_fees'. (Error='ignore_fees')
Traceback (most recent call last):
  File "/usr/local/bin/charge-lnd", line 11, in <module>
    load_entry_point('charge-lnd==0.2.8', 'console_scripts', 'charge-lnd')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = import(self.module_name, fromlist=['name'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/charge_lnd-0.2.8-py3.7.egg/charge_lnd/charge_lnd.py", line 159, in <module>
  File "/usr/local/lib/python3.7/dist-packages/charge_lnd-0.2.8-py3.7.egg/charge_lnd/charge_lnd.py", line 54, in main
ValueError: not enough values to unpack (expected 6, got 5)Unknown strategy 'ignore_fees' in policy 'Opener-HTLC-Slow'
Error executing strategy 'ignore_fees'. (Error='ignore_fees')
Traceback (most recent call last):
  File "/usr/local/bin/charge-lnd", line 11, in <module>
    load_entry_point('charge-lnd==0.2.8', 'console_scripts', 'charge-lnd')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = import(self.module_name, fromlist=['name'], level=0)
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/usr/local/lib/python3.7/dist-packages/charge_lnd-0.2.8-py3.7.egg/charge_lnd/charge_lnd.py", line 159, in <module>
  File "/usr/local/lib/python3.7/dist-packages/charge_lnd-0.2.8-py3.7.egg/charge_lnd/charge_lnd.py", line 54, in main
ValueError: not enough values to unpack (expected 6, got 5)_

Thank you for considering update soon.

**Comment by accumulator** [comment]
I wasn't involved in integrating charge-lnd in lightning shell. Indeed, 0.2.8 is outdated. I've linked the corresponding issue below.

https://github.com/ibz/lightning-shell/issues/24
