### ISSUE TITLE
`ignore_fees` strategy attempts to divide an integer by a string

### ISSUE THREAD

**Issue by Fopstronaut** [accumulator/charge-lnd#116]
Commit: 676f922
LND version: 0.18.0-beta

charge-lnd doesn't feel like applying the `ignore_fees` strategy.
```
Traceback (most recent call last):
  File "/.../.local/bin/charge-lnd", line 5, in <module>
    from charge_lnd.charge_lnd import main
  File "/.../.venv/lib/python3.12/site-packages/charge_lnd/charge_lnd.py", line 189, in <module>
    success = main()
              ^^^^^^
  File "/.../.venv/lib/python3.12/site-packages/charge_lnd/charge_lnd.py", line 100, in main
    lnd.update_chan_policy(channel.chan_id, chp)
  File "/.../.venv/lib/python3.12/site-packages/charge_lnd/lnd.py", line 162, in update_chan_policy
    fee_rate=chp.fee_ppm/1000000 if chp.fee_ppm is not None else my_policy.fee_rate_milli_msat/1000000,
             ~~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for /: 'str' and 'int'
```

**Comment by feelancer21** [comment]
I think the reason was this commit. 
https://github.com/accumulator/charge-lnd/commit/9fed8d3b8af30414c69637782de78088774aece8

Should be easy to fix. I give it a shot.
