### ISSUE TITLE
How can I match htlcs_out > x ?

### ISSUE THREAD

**Issue by mfbrj** [accumulator/charge-lnd#99]
I would like to use a policy based on ranges of htlc_out activity, such as:
```
[range-1]
chan.activity_period=24h
chan.htlcs_out > 30

strategy = proportional
base_fee_msat = 300
min_fee_ppm = 310
max_fee_ppm = 500
min_fee_ppm_delta = 10

[range-2]
chan.activity_period=24h
chan.htlcs_out >= 25

strategy = proportional
base_fee_msat = 250
min_fee_ppm = 192
max_fee_ppm = 310
min_fee_ppm_delta = 10

```

How can I configure this policy with current parameters supported by charge-lnd?

I tried to use:
```
[range-1]
chan.activity_period=24h
chan.max_htlcs_out > 30

strategy = proportional
base_fee_msat = 300
min_fee_ppm = 310
max_fee_ppm = 500
min_fee_ppm_delta = 10
```
But I got these error:
```
Traceback (most recent call last):
  File "/usr/local/bin/charge-lnd", line 5, in <module>
    from charge_lnd.charge_lnd import main
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/charge_lnd.py", line 165, in <module>
    success = main()
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/charge_lnd.py", line 30, in main
    config = Config(arguments.config)
  File "/usr/local/lib/python3.9/site-packages/charge_lnd/config.py", line 22, in __init__
    self.config.read_file(f)
  File "/usr/local/lib/python3.9/configparser.py", line 718, in read_file
    self._read(f, source)
  File "/usr/local/lib/python3.9/configparser.py", line 1116, in _read
    raise e
configparser.ParsingError: Source contains parsing errors: '/config-charge/routing.config'
	[line  3]: 'chan.max_htlcs_out > 30\n'
```

**Comment by accumulator** [comment]
Yes, it is confusing :) 

Due to the simple ini-style config file it is not trivial to add comparison operators like e.g. < and >=

You have to use `chan.min_htlcs_out = x` when you mean `chan.htlcs_out >= x`, and 
`chan.max_htlcs_out = y` when you mean `chan.htlcs_out <= y`

So a rule of `5 <= chan.htlcs_out <= 10` would be matched by these two rules:
```
chan.min_htlcs_out = 5
chan.max_htlcs_out = 10

```

**Comment by mfbrj** [comment]
It didn't work.

I used this config:
```
[range-1]
chan.activity_period=24h
chan.min_htlcs_out = 30

strategy = proportional
base_fee_msat = 300
min_fee_ppm = 310
max_fee_ppm = 500
min_fee_ppm_delta = 10

[range-2]
chan.activity_period=24h
chan.min_htlcs_out = 25
chan.max_htlcs_out = 30

strategy = proportional
base_fee_msat = 250
min_fee_ppm = 192
max_fee_ppm = 310
min_fee_ppm_delta = 10

[range-3]
chan.activity_period=24h
chan.min_htlcs_out = 20
chan.max_htlcs_out = 25

strategy = proportional
base_fee_msat = 200
min_fee_ppm = 119
max_fee_ppm = 192
min_fee_ppm_delta = 10

[range-4]
chan.activity_period=24h
chan.min_htlcs_out = 15
chan.max_htlcs_out = 20

strategy = proportional
base_fee_msat = 15
min_fee_ppm = 74
max_fee_ppm = 119
min_fee_ppm_delta = 5

[range-5]
chan.activity_period=24h
chan.min_htlcs_out = 10
chan.max_htlcs_out = 15

strategy = proportional
base_fee_msat = 100
min_fee_ppm = 46
max_fee_ppm = 74
min_fee_ppm_delta = 5

[range-6]
chan.activity_period=24h
chan.min_htlcs_out = 5
chan.max_htlcs_out = 10

strategy = proportional
base_fee_msat = 50
min_fee_ppm = 29
max_fee_ppm = 46
min_fee_ppm_delta = 5

[range-7]
chan.activity_period=24h
chan.min_htlcs_out = 0
chan.max_htlcs_out = 5

strategy = proportional
base_fee_msat = 0
min_fee_ppm = 2
max_fee_ppm = 29
min_fee_ppm_delta = 3
```

It matched nothing. The logs print nothing.

**Comment by accumulator** [comment]
try with -v cmdline option

**Comment by mfbrj** [comment]
```
798491x1602x0 [ln.mtpelerin.com|020a919e4684a3678bd5d5fb21752ca19f9700214bf399abca72190c29664ad551]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         27
  min_htlc_msat:   1000
  max_htlc_msat:   3762000000
  time_lock_delta: 100
798484x1111x0 [i'llTryAnythingOnce|020d1617e27ac022395352f2b3774969593d3d6ddff6fb117d820a9dda8da45217]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         21
  min_htlc_msat:   1000000
  max_htlc_msat:   3800000000
  time_lock_delta: 100
800060x3056x2 [John Galt|021c4c58a15fa847720cbc02775df975c1dd6994be443f6eb1392275559c05db7f]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         14
  min_htlc_msat:   1000
  max_htlc_msat:   6930000000
  time_lock_delta: 100
800163x1109x1 [MerchantConnectHUB|023e09c43b215bd3dbf483bcb409da3322ea5ea3b046f74698b89ee9ea785dd30a]
  policy:          range-5
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   100
  fee_ppm:         69
  min_htlc_msat:   1000
  max_htlc_msat:   3960000000
  time_lock_delta: 100
799847x1145x1 [deezy.io ⚡✨|024bfaf0cabe7f874fd33ebf7c6f4e5385971fc504ef3f492432e9e3ec77e1b5cf]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         2
  min_htlc_msat:   1000
  max_htlc_msat:   1980000000
  time_lock_delta: 100
800025x1901x0 [Bomlo.Lightning|0290f49e1eaba3e141453b253e5d63024381db278951e21886d1443e92ad7fdba2]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         28
  min_htlc_msat:   1000
  max_htlc_msat:   990000000
  time_lock_delta: 100
800021x1123x0 [LiquidBitch|02a624a8019bb184d208045c07e511a571dfd6d9f1fb6c590c0f8ce5c424748f38]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         15
  min_htlc_msat:   1000
  max_htlc_msat:   990000000
  time_lock_delta: 100
798494x1457x0 [ElenPAY⚡|02c5544a361bfe1f025f29e83d092e4c83feaf5f750af59a0b1ff0591ebc0beedc]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         19
  min_htlc_msat:   1000
  max_htlc_msat:   3762000000
  time_lock_delta: 100
799030x1850x1 [SiameseCat|02cdf44d535c70007f7995260c1cbce9cadd5da31af076b21f42f15ea3bcb4d8a7]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         5
  min_htlc_msat:   1000
  max_htlc_msat:   2970000000
  time_lock_delta: 100
798508x1342x0 [California-Sierra|02d1395b23225c03b274cd95508ce28abeb2928c38963bbf401412f556a21f90c9]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         23
  min_htlc_msat:   1000
  max_htlc_msat:   3762000000
  time_lock_delta: 100
799318x869x1  [bipa|02fb79c3a9121d85b126687bd111eaebf21aaaaa5cbf232e2b6c3bdf8803f40182]
  policy:          range-6
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   50
  fee_ppm:         45
  min_htlc_msat:   1000
  max_htlc_msat:   2970000000
  time_lock_delta: 100
798903x859x0  [NodeRunners Brasil⚡🍠🟣|0320534540971752234228e323faa4f1314f8751e05029413c8ae34da209f8e497]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         2
  min_htlc_msat:   1000
  max_htlc_msat:   5940000000
  time_lock_delta: 100
799857x526x1  [noah-btc-node-m-01a|0339a3fb0e1d40503e38be50fbaad700ae730bea86bf81b8e2d1dc83d768ff467f]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         28
  min_htlc_msat:   1000
  max_htlc_msat:   1980000000
  time_lock_delta: 100
800032x2544x0 [Sunny Sarah ☀️|03423790614f023e3c0cdaa654a3578e919947e4c3a14bf5044e7c787ebd11af1a]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         2
  min_htlc_msat:   100000
  max_htlc_msat:   4950000000
  time_lock_delta: 100
800149x1813x1 [lightning honk|0359f88efc91da26b443d2fb611b6240531dc662ff6c789fedebeff45cf04833ae]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         13
  min_htlc_msat:   1000
  max_htlc_msat:   2475000000
  time_lock_delta: 100
798959x2927x1 [WalletOfSatoshi.com|035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226]
  policy:          range-5
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   100
  fee_ppm:         73
  min_htlc_msat:   1000
  max_htlc_msat:   5940000000
  time_lock_delta: 100
798821x189x1  [🇨🇭 Swiss Bitcoin Pay|03c181e13a09a649c13f60ea3ddbeefc66123c43280da8eebc19f54445f35173ca]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         2
  min_htlc_msat:   1000
  max_htlc_msat:   9900000000
  time_lock_delta: 100
800988x1737x1 [LunaLightning🌙⚡|03c673ca36cbae6becd609e827745961a92c6e4661f6200c463b8c101691a7e91a]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         28
  min_htlc_msat:   1000
  max_htlc_msat:   4950000000
  time_lock_delta: 100
799027x1902x0 [Lightning.Watch|03e691f81f08c56fa876cc4ef5c9e8b727bd682cf35605be25d48607a802526053]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         2
  min_htlc_msat:   1000
  max_htlc_msat:   19800000
  time_lock_delta: 144
800050x1704x1 [IsleOfBits|03f1822e549f078b11c7be24f673ac684b82d2019e8f22fc056169ad2c79a0b41e]
  policy:          range-7
  strategy:        proportional
  channel status:  enabled
  base_fee_msat:   0
  fee_ppm:         3
  min_htlc_msat:   1000
  max_htlc_msat:   1782000000
  time_lock_delta: 100
  ```
  
  There is no indication of of `min_htlcs_out` or `min_htlcs_out`

**Comment by accumulator** [comment]
correct, only the channel parameters are shown in the output

**Comment by mfbrj** [comment]
I notice that there is one channel that is not matching in any policy. This channel was open in last than 24h. I need to use `chan.activity_period_ignore_channel_age`, right?

**Comment by accumulator** [comment]
Yes

**Comment by mfbrj** [comment]
I set `chan.activity_period_ignore_channel_age = true` in all policies, but the recent channel doesn't match.

**Comment by mfbrj** [comment]
Please desconsider. It matches after other tries.

**Comment by mfbrj** [comment]
@accumulator the policies are working as expected. Thanks for your support.
